version: '2'

services:
  python-sgx:
    image: enclaive/python-sgx
    container_name: "python-sgx"
    build:
      context: .
    ports:
      - "443:443"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
