version: '2'

services:
  python-sgx:
    image: enclaive/python-sgx
    container_name: "python-sgx"
    build:
      context: .
    ports:
      - "443:443"
      - "8888:8888"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"
    volumes:
      - ./certs:/app/certs
      - ./.env:/app/config/.env
    environment:
      - ENV_FILE=/app/config/.env
    # command: python3 main.py --host 0.0.0.0 --port 8888 --ssl-keyfile /app/certs/key.pem --ssl-certfile /app/certs/cert.pem --env-file /app/config/.env